In [1]:
import pandas as pd

In [2]:
# 2 main data types
# Series - 1 dimensional
series = pd.Series(["BMW", "Toyota", "Honda"])
colors = pd.Series(["Red", "Blue", "White"])
series
colors

0      Red
1     Blue
2    White
dtype: str

In [3]:
# DataFrame - 2 dimensional
car_data = pd.DataFrame({"Car make":series, "Color": colors})
car_data

  Car make  Color
0      BMW    Red
1   Toyota   Blue
2    Honda  White

In [4]:
# Import data from CSV
# Note: axis 0 = rows, axis 1 = columns
car_sales = pd.read_csv("car-sales.csv")
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [5]:
# Exporting a DataFrame
# The 'index' parameter is set to False to avoid exporting the index column to the CSV file
car_sales.to_csv("exported-car-sales.csv", index=False)

# Describe Data

In [6]:
car_sales.dtypes

Make               str
Colour             str
Odometer (KM)    int64
Doors            int64
Price              str
dtype: object

In [7]:
car_columns =car_sales.columns
car_columns

Index(['Make', 'Colour', 'Odometer (KM)', 'Doors', 'Price'], dtype='str')

In [8]:
car_sales.index

RangeIndex(start=0, stop=10, step=1)

In [9]:
car_sales.describe()

       Odometer (KM)      Doors
count      10.000000  10.000000
mean    78601.400000   4.000000
std     61983.471735   0.471405
min     11179.000000   3.000000
25%     35836.250000   4.000000
50%     57369.000000   4.000000
75%     96384.500000   4.000000
max    213095.000000   5.000000

In [ ]:
car_sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Make           10 non-null     str
 1   Colour         10 non-null     str
 2   Odometer (KM)  10 non-null     int64
 3   Doors          10 non-null     int64
 4   Price          10 non-null     str
dtypes: int64(2), str(3)
memory usage: 532.0 bytes